export default function Terms() {
  return (
    <div className="page-shell" style={{ paddingTop: 68 }}>
      <div className="policy-hero">
        <div className="policy-last-update">📅 Last Updated: April 2025</div>
        <h1 style={{ fontSize: "clamp(2rem,5vw,3rem)", fontWeight: 900, letterSpacing: "-0.03em", marginBottom: 16 }}>
          Terms &amp; Conditions
        </h1>
        <p style={{ color: "var(--muted)", lineHeight: 1.75 }}>
          Please read these terms carefully before using ForecastIQ. By accessing this platform, 
          you agree to be bound by the terms described below.
        </p>
      </div>

      <div className="policy-body">
        <div className="policy-divider" />

        <div className="policy-section">
          <h2>1. Acceptance of Terms</h2>
          <p>By accessing or using ForecastIQ ("the Platform"), you agree to comply with and be bound by these Terms and Conditions. If you do not agree to these terms, please do not use the Platform. These terms apply to all visitors, users, and others who access or use ForecastIQ.</p>
        </div>

        <div className="policy-section">
          <h2>2. Nature of the Platform</h2>
          <p>ForecastIQ is an academic demonstration project developed as a capstone project by students. The platform provides AI-powered demand forecasting, inventory optimization calculations, and stockout risk assessments based on machine learning models trained on the Sample Superstore dataset.</p>
        </div>

        <div className="policy-section">
          <h2>3. Disclaimer of Warranties</h2>
          <p>The Platform is provided "as is" and "as available" without any warranties of any kind, either express or implied. We do not guarantee:</p>
          <ul>
            <li>The accuracy, completeness, or usefulness of any predictions or recommendations</li>
            <li>That the service will be uninterrupted, timely, or error-free</li>
            <li>That the results obtained from the Platform will be accurate or reliable</li>
            <li>That any errors in the software will be corrected</li>
          </ul>
        </div>

        <div className="policy-section">
          <h2>4. Limitation of Liability</h2>
          <p>ForecastIQ and its team members shall not be liable for any direct, indirect, incidental, special, or consequential damages resulting from your use of or inability to use the Platform, including but not limited to business losses, inventory mismanagement, or financial losses based on predictions made by the Platform.</p>
        </div>

        <div className="policy-section">
          <h2>5. Educational Purpose Only</h2>
          <p>All forecasts, recommendations, EOQ calculations, and risk assessments generated by this Platform are for <strong>educational and demonstration purposes only</strong>. They should not be used as the sole basis for real business decisions. Always consult qualified supply chain professionals for critical inventory management decisions.</p>
        </div>

        <div className="policy-section">
          <h2>6. Intellectual Property</h2>
          <p>All content, code, models, and design elements of ForecastIQ are the intellectual property of the ForecastIQ team (Vishal Raj, Divyanshi, Monty Gaurav, and Dhruv). The Sample Superstore dataset is publicly available and belongs to its respective owners.</p>
        </div>

        <div className="policy-section">
          <h2>7. Third-Party Services</h2>
          <p>The Platform uses third-party services including Google Fonts for typography and Render for backend hosting. Your use of these embedded services is subject to their respective terms and privacy policies.</p>
        </div>

        <div className="policy-section">
          <h2>8. Changes to Terms</h2>
          <p>We reserve the right to modify these terms at any time. Continued use of the Platform after changes constitutes acceptance of the updated terms.</p>
        </div>

        <div className="policy-section">
          <h2>9. Contact</h2>
          <p>For questions about these terms, please reach out to the ForecastIQ team via the project repository or institution contact channels.</p>
        </div>
      </div>
    </div>
  );
}
